### PR TITLE
fix errors on linux

### PR DESCRIPTION
**Pull request by loooph**
This should fix the errors caused by different GLSL versions / dialects on the Linux version of OBS mentioned in #1 . Sorry for the huge number of changes, I could not keep myself from removing the trailing whitespace :wink:

### CODE REVIEW

**Comment by alex-ong** [comment]
What were the actual changes, there's so much whitespace change that all it looks like is line ending changes to me; is there a specific line number i should look at? :D

**Comment by alex-ong** [comment]
Oh i see you helpfully did it in two commits, yes looks great

**Comment by alex-ong** [comment]
Alright, for windows, it doesn't know what mod is
`09:08:36.210: C:\Program Files\obs-studio\bin\64bit\ (Pixel shader, technique Draw, pass 0)(424,22-67): error X3004: undeclared identifier 'mod'`
Is there some modular way of defining mod if its undefined in c shader land?

**Comment by alex-ong** [comment]
Alright, add this and i can accept PR:
```
float my_mod(float a, float b)
{
	return a - (b * floor(a/b));
}
```
**Then call it instead of mod**. Stupid linux/windows glsl incompatibility.

Also if you know how to load other .shader from a shader, let me know, since 99% of the functions are the same but i never figured out how to import other shader functions ;(. In unity3d i used #include but i have no idea if it works here...
edit: #include "C:/dev/nestrissharper/module.shader" works, but #include "module.shader" i think reads from `C:/program files/OBS/` which is yikes.

I just want modular code :(

**Comment by loooph** [comment]
I think the problem with the include paths is caused by obs-shaderfilter looking for files relative to its working directory which is where OBS is located.
Using a preprocessor could work (on linux there is `cpp` for the C preprocessor which can handle stuff like `#include`): split the shader files into development files which need to be preprocessed and release files which can be loaded by obs-shaderfilter. Preprocessing could be done automatically by a pre-commit hook but I'm not sure if that would be a good workflow.

**Comment by alex-ong** [comment]
I tested nestris-stencil.shader and digits-02.shader. I'm going to assume you did the rest fine from just looking at the code :kappa:
Also digits don't use mod 👍

**Pull request merged**
